---
- name: Get latest Elastic Beanstalk environment DNS
  hosts: anguler_server
  gather_facts: no
  tasks:
    - name: Execute AWS CLI command to get Elastic Beanstalk environment DNS
      command: >
        aws elasticbeanstalk describe-environments --query "Environments | sort_by(@, &DateCreated) | [-1].CNAME" --output text
      register: eb_dns_output

    - name: Show Elastic Beanstalk DNS
      debug:
        msg: "The latest Elastic Beanstalk environment DNS is: {{ eb_dns_output.stdout }}"
      
    - name: clone github repository
      git:
        repo: 'git@github.com:dilafar/angular-aws-cloud.git'
        dest: ./app-repo
        version: master
      register: git_status

    - name: Replace apiServerUrl with the new value
      lineinfile:
        path: "/home/ubuntu/app-repo/src/environments/environment.ts"
        regexp: '^(\s*apiServerUrl:\s*").*(?=")'
        line: ' apiServerUrl: "{{eb_dns_output.stdout}}/api"'
        backup: yes
