---
- name: install java and net-tools
  hosts: nexus_server
  become: yes
  tasks:
    - name: update apt repo and cache
      yum:
        update_cache: yes
    - name: install java jdk 8
      yum:
        name: java-1.8.0-openjdk-devel
        state: present
    - name: install net-tools
      yum:
        name: net-tools
        state: present

- name: unarchive nexus file
  hosts: nexus_server
  become: yes
  tasks:
    - name: download file
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_url
    - debug:
        msg: "{{download_url}}"
    - name: ensure nexus folder is already created
      stat:
        path: /opt/nexus
      register: nexus_stat
    - name: unarchive nexus file
      unarchive:
        src: "{{download_url.dest}}"
        dest: /opt/
        remote_src: yes
      when: not nexus_stat.stat.exists
    - name: rename to nexus folder
      find:
        paths: /opt/
        patterns: "nexus-*"
        file_type: directory
      register: nexus_folder
    - name: mv nexus
      shell: mv {{nexus_folder.files[0].path}} /opt/nexus
      when: not nexus_stat.stat.exists

- name: create user nexus and assign permission
  hosts: nexus_server
  become: yes
  tasks:
    - name: create group
      group:
        name: nexus
        state: present
    - name: create user
      user:
        name: nexus
        group: nexus
    - name: nexus file owner
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: sonar-type file owner
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: change run as user to nexus
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"
    - name: Create Nexus systemd service file
      template:
        src: templates/nexus.service.j2
        dest: /etc/systemd/system/nexus.service
        mode: "a+x"
      notify:
        - Reload systemd
        - Enable and start Nexus service

  handlers:
    - name: Reload systemd
      systemd_service:
        daemon_reload: true
    - name: Enable and start Nexus service
      systemd_service:
        name: nexus
        state: started
        enabled: true

- name: Verify nexus running
  hosts: nexus_server
  tasks:
    - name: check with the ps
      shell: ps aux | grep nexus
      register: app_status
    - debug:
        msg: "{{app_status.stdout_lines}}"
    - name: wait one minute
      pause:
        minutes: 1
    - name: check with netstat
      shell: netstat -tulpena | grep postgres
      register: app_status
    - debug:
        msg: "{{app_status.stdout_lines}}"
