---
- name: install docker and docker compose
  hosts: docker_server
  become: yes
  tasks:
    - name: update cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - python3-pip
          - acl
        state: present

    - name: Install specific version of Docker SDK for Python
      pip:
        name:
          - docker
          - docker-compose

  roles:
    - install_docker
    - install_docker_compose

- name: start docker service
  hosts: docker_server
  become: yes
  roles:
    - start_docker

- name: create new linux user
  hosts: docker_server
  become: yes
  roles:
    - create_user

- name: run test docker image
  hosts: docker_server
  become: yes
  become_user: fadhil
  roles:
    - start_containers
