- name: create docker key file directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: install docker key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: a+r

- name: install repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: update cache again after adding Docker repo
  apt:
    update_cache: yes

- name: List available Docker packages
  apt:
    name: docker-ce
    state: latest
