services:
  java-app:
    image: fadhiljr/currency-exchange:1.1.0-RELEASE
    ports:
      - 8000:8000
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd
